services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=pge'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5438:5432'
    networks:
      - webapp
  api:
    image: oicapivara/gerenciador-processos:0.1
    hostname: api
    ports:
      - "8080:8080"
    networks:
      - webapp
    depends_on:
      - postgres

networks:
  webapp: